apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public-disclosures
  description: >-
    Repository contains required information by MITRE to reveal details of the
    CVE
  annotations:
    backstage.io/techdocs-ref: .
    sonarqube.org/project-key: com.wandera.public-disclosures
  tags:
    - security
    - cve
spec:
  type: website
  lifecycle: production
  owner: appsec
  system: public-disclosures
